######################################################################
# Automatically generated by qmake (3.1) Tue Dec 24 09:33:44 2019
######################################################################


TEMPLATE = app
TARGET = simpleapplication

QT = core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

SOURCES +=  main.cpp
